### ISSUE TITLE
Status badge shows "build: mixed" even though the workflow was successful

### ISSUE THREAD

**Issue by xJREB** [JasonEtco/action-badges#10]
When I visit the URL for the badge for my public repo (https://action-badges.now.sh/xJREB/microservices-runtime-analysis), I see the correct "build: passing" badge. However, on Github in my README (https://github.com/xJREB/microservices-runtime-analysis), I see a different badge with "build: mixed". Any idea what is happening there? Did I inlcude the badge somehow wrongly?

```markdown
[![Actions Status](https://action-badges.now.sh/xJREB/microservices-runtime-analysis)](https://github.com/xJREB/microservices-runtime-analysis/actions)
```

**Comment by JasonEtco** [comment]
Shows as passing for me! It's likely just a caching issue, the caching headers can be pretty fickle. I'll close this out since there's nothing actionable (heh, actionable).

![image](https://user-images.githubusercontent.com/10660468/60732768-e74b1600-9f18-11e9-8789-af5a91532471.png)

**Comment by xJREB** [comment]
Yeah, like I said, if I visit the URL shown in your screenshot, the badge looks fine. However, it does NOT at my repository site: 
![image](https://user-images.githubusercontent.com/3702778/60733352-e3d18200-9f4c-11e9-98b4-2e2de5165f52.png)

Any idea why? I'm pretty sure it's not related to caching. Already tried different browsers and even from different locations.

**Comment by JasonEtco** [comment]
It's actually _GitHub_ caching the image, not your browser - if you'll notice, GitHub grabs the image and saves it to its own domain:

![image](https://user-images.githubusercontent.com/10660468/60734100-c684bf80-9f1c-11e9-959b-c074db8016a5.png)

This is done for security reasons, but can cause images to fall out of date in weird ways. This repo uses the same caching headers as [badgen](https://badgen.net/), so as far as I know that's the best we can do 😬

**Comment by xJREB** [comment]
Ah, very interesting... 🤔 Thanks for the info and the support! I'll keep an eye on it, maybe it'll resolve itself in some time.
