### ISSUE TITLE
Add branch selection

### ISSUE THREAD

**Issue by mourner** [JasonEtco/action-badges#12]
> Get a status badge for all GitHub Action runs on the `master` branch of a repository:

It would be great to add the ability to specify the branch to check, e.g. `?branch=foo`, like with Travis/Circle CI badges.

Thanks you for a nice tool!

**Comment by tunnckoCore** [comment]
Good idea. Btw, we will implement github actions badges on @badgen soon, stay tuned both of you :)

**Comment by JasonEtco** [comment]
Closing this because GitHub Actions [now has official badge support](https://help.github.com/en/articles/configuring-a-workflow#adding-a-workflow-status-badge-to-your-repository)!
