### ISSUE TITLE
More information

### ISSUE THREAD

**Issue by PatMyron** [JasonEtco/action-badges#6]
https://action-badges.now.sh/gr2m/twitter-together

It'd be interesting if it linked to builds:
https://github.com/nock/twitter/runs/76823945
https://github.com/probot/twitter/runs/82446300

or summarized with details like `2/2 failing`

**Comment by JasonEtco** [comment]
Oooh showing the `2/2 ___` would be really cool. Would definitely be open to a PR for something like that. Linking to the builds isn't really something that this service can do, it's up to the markdown surrounding the requested image. We _could_ do a redirect kinda thing, but that's separate from the badge generation.

**Comment by jletey** [comment]
> Would definitely be open to a PR for something like that.

@JasonEtco I'd be happy to give this a shot (I actually see a way of doing it) ... but I don't have access to the actions beta 😢, so I won't be able to test anything

Just a quick question ... for example, if there are two tests (one passing, one failing) ... do you want the badge to say "1/2 failing" or "1/2 passing"? What about for any permutation of responses?
