### ISSUE TITLE
Support review of last action result only

### ISSUE THREAD

**Issue by hit2hat** [JasonEtco/action-badges#8]
Url with this feature would see like {owner}/{repo}/?only_last=true

**Comment by JasonEtco** [comment]
Hey @hit2hat, can you elaborate a bit? I'm not sure I understand what `only_last` would do in practice.

**Comment by hit2hat** [comment]
If that param was given, your app check only latest result
(Now you check all results judging by the code, see image below)
<img width="587" alt="Снимок экрана 2019-05-12 в 21 31 21" src="https://user-images.githubusercontent.com/42957391/57586343-50a43f00-74fd-11e9-9688-6df1fc6343e2.png">

P.S. excuse me for bad english

**Comment by hit2hat** [comment]
I can try to show my idea in code, If you're not understood my bad description 😞
