### ISSUE TITLE
Enable for private repos?

### ISSUE THREAD

**Issue by joshmanders** [JasonEtco/action-badges#9]
What would it take to make this work for private repos? I'm not 100% sure how now.sh stores data on requests, but I know some badge services allow you to pass an api key, would it be possible for us to make that work here too?

```![badge](https://action-badges.now.sh/JasonEtco/example-repo?token=$GITHUB_TOKEN)```

**Comment by JasonEtco** [comment]
Yeah that's probably how it'd work - a PR for that would be 👌, the token would be used here:

https://github.com/JasonEtco/action-badges/blob/4c18c72039e833b087ab982aab6bed1fde56e0e1/lib/get-check-suites.js#L22

Something like:

```js
authorization: `token ${QUERY_PROVIDED_TOKEN || process.env.GITHUB_TOKEN}`
```

The one that's set as `process.env.GITHUB_TOKEN` is a personal access token to avoid rate limiting, so it's still needed if no token is provided.

**Comment by jletey** [comment]
@joshmanders I can open up a PR for you if you're busy!

**Comment by joshmanders** [comment]
@johnletey I have not even begun so if you'd like to, it's all yours!

**Comment by JasonEtco** [comment]
Closing this because GitHub Actions [now has official badge support](https://help.github.com/en/articles/configuring-a-workflow#adding-a-workflow-status-badge-to-your-repository)!
